<a href="https://colab.research.google.com/github/gauriwagare/Data_Science_Lab/blob/main/practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

TO CREATE AN ARRAY

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

2D ARRAY


In [6]:
arr1=[1,2]
arr2=[3,4]
arr3=np.array([arr1,arr2])
arr3


array([[1, 2],
       [3, 4]])

MATRIX

In [7]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

DETERMINANT

In [8]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [10]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
np.linalg.det(a)

array([0.])

INVERSE OF MATRIX

In [9]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

LINEAR EQUATION USING NUMPY

In [13]:
A=np.array([[2,3],[4,5]])
B=np.array([10,20])
X=np.linalg.solve(A,B)
print(X)


[5. 0.]
